[package]
name = "projectx_game"
version = "0.1.0"
authors = ["louisdewardt <contact@louis.dewardt.uk>"]
edition = "2018"

[dependencies]
ggez = "0.5"
rand = "0.7"

serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0"
