[package]
name = "db"
version = "0.1.0"
authors = ["louisdewardt <contact@louis.dewardt.uk>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4"
