[package]
name = "tournament"
version = "0.1.0"
authors = ["louisdewardt <contact@louis.dewardt.uk>"]
edition = "2018"

[dependencies]
model = { path = "../model" }
tungstenite = "0.11.1"
serde = "1.0"
